
<div class="sidebar widget">
    <div class="menu">
        <a href="/admin">
            <span class="headding"><i class="fa fa-gears"></i> Quản lý 
            </span></a>
        <ul>
            <li> 
                <a href="/admin/categories">
                    <span class="headding">
                        <i class="fa fa-gears"></i> Danh mục
                    </span>
                </a>
            </li>
            <li>
                 <a href="/admin/manufacturers">
                    <span class="headding">
                        <i class="fa fa-gears"></i> Nhà sản xuất
                    </span>
                </a>
            </li>
            <li>
                 <a href="/admin/products">
                    <span class="headding">
                        <i class="fa fa-gears"></i> Sản phẩm
                    </span>
                </a>
                <ul>
                    <li><a href="/admin/colors">Màu sắc</a></li>
                    <li><a href="/admin/size">Kích thước </a></li>
                </ul>
            </li>
             <li>
                 <a href="/admin/categories">
                    <span class="headding">
                        <i class="fa fa-gears"></i> Giỏ hàng
                    </span>
                </a>
            </li>
        </ul>
    </div>
</div>