<header class="clearfix">
    <div class="container">	
	<div class="row">
	<div class="col-lg-6">
       <a href="/">
	<div class="companyinfo" style="margin:0px">
	<h2>MAISON</h2>
        </div>
       </a>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-6">
            <a href="/admin">
           <div class="companyinfo" style="margin:0px">
           <h2><span>MAISON</span>-quản lý website</h2>
            </div>
            </a>
        </div>
        </div><!-- /.col-lg-6 -->
</div>
</div>
</header>