
    <section class="content-footer">
        <div class="container">
            <div class="present">
                <div class="row">
                    <div class="col-md-4">
                        <div class="main">
                            <div class="icon-circle">
                                <i class="fa fa-truck fa-3x"></i>

                            </div>
                            <h2>Giao hàng miễn phí</h2>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="main">
                            <div class="icon-circle">
                                <i class="fa fa-usd fa-3x"></i>

                            </div>
                            <h2>Thanh toán khi giao dịch</h2>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="main">
                            <div class="icon-circle">
                                <i class="fa fa-support fa-3x"></i>

                            </div>
                            <h2>Hỗ trợ trực tuyến 24/7</h2>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <footer>
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <div class="widget">
                            <div class="menu">
                                <span class="headding">Menu</span>
                                <ul>
                                    <li><a href="#">Trang chủ</a></li>
                                    <li><a href="#">Đồ nam</a></li>
                                    <li><a href="#">Đồ nữ</a></li>
                                    <li><a href="#">Thương hiệu</a></li>
                                    <li><a href="#">Cửa hàng</a></li>
                                    <li><a href="#">Khuyến mãi</a></li>
                                    <li><a href="#">Tin mới</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="widget">
                            <div class="menu">
                                <span class="headding">Tài khoản</span>
                                <ul>
                                    <li><a href="#">Sản phẩm đã đặt</a></li>
                                    <li><a href="#">Thanh toán của bạn</a></li>
                                    <li><a href="#">Giỏ hàng của bạn</a></li>
                                    <li><a href="#">Thiết lập tài khoản</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="widget">
                            <div class="menu">
                                <span class="headding">Sản phẩm</span>
                                <ul>
                                    <li><a href="#">Sản phẩm mới</a></li>
                                    <li><a href="#">Hàng đang HOT</a></li>
                                    <li><a href="#">Sản phẩm đang khuyến mãi</a></li>
                                    <li><a href="#">Sản phẩm được ưa chuộng</a></li>

                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="widget">
                            <div class="contact">
                                <span class="headding">Liên hệ</span>
                                <div class="main">
                                    <h5 class="text-uppercase"><i class="fa fa-map-marker"></i> Trụ sở chính:</h5>
                                    <p>Tầng 19, Toà nhà Vincom Center,<br> Khu văn phòng 72 Lê Thánh Tôn, P.Bên Nghé, Quận 1, Tp.HCM, Việt Nam</p>
                                    <h5 class="text-uppercase"><i class="fa fa-phone"></i> TEL  <a href="#">08 3936 9424</a></h5>
                                    <h5 class="text-uppercase"><i class="fa fa-fax"></i> FAX  <a href="#">08 3936 9420</a></h5>
                                    <h5><i class="fa fa-envelope"></i> EMAIL  <a href="#">ductranxuan.29710@gmail.com</a></h5>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!--end footer-top -->

        <div class="footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="circle">
                            <a>
                                <i class="fa fa-facebook"></i>
                            </a>
                        </div>
                        <div class="circle">
                            <a>
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h5 class="text-uppercase" style="display: inline;">Nhận thông tin </h5>
                        <form class="form-inline"  style="display: inline-block;float:right;">
                            <div class="input-group">

                                <input type="text" class="form-control" aria-label="..." placeholder="">
                                <div class="input-group-btn">
                                    <button class="btn btn-primary">
                                        Gửi
                                    </button>
                                </div>
                            </div><!-- /input-group -->
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p>Copyright 2015 &copy; Tran Xuan Duc All Rights Reserved.<p>
                    </div>
                    <div class="col-md-6">
                        <ul>
                            <li><a><i class="fa fa-cc-paypal fa-2x"></i></a></li>
                            <li><a><i class="fa fa-cc-visa fa-2x"></i></a></li>
                            <li><a><i class="fa fa-cc-mastercard fa-2x"></i></a></li>
                            <li><a><i class="fa fa-cc-amex fa-2x"></i></a></li>
                            <li><a><i class="fa fa-cc-discover fa-2x"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    
    <?php echo $this->headScript() ?>  

    <script>
        $('#slideshow').slick();

        $(document).ready(function () {
            $(".stars-default").rating('create', {value: 3});
        });
    </script>

</body>
</html>
