<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
    </head>
</head>
<body>
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <div class="social">
                            <div class="circle">
                                <a href="http://facebook.com/ducsatthuttd">
                                    <i class="fa fa-facebook fa-lg"></i>
                                </a>
                            </div>
                            <div class="circle">
                                <a href="http://facebook.com/ducsatthuttd">
                                    <i class="fa fa-google-plus fa-lg"></i>
                                </a>
                            </div>
                            <div class="circle">
                                <a href="http://facebook.com/ducsatthuttd">
                                    <i class="fa fa-envelope fa-lg"></i>
                                </a>
                            </div>
                            <div class="text">
                                <a href="mailto:ductranxuan.29710@gmail.com">ductranxuan.29710@gmail.com</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="account">
                            <div class="btn-group">
                                <a type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Tài khoản của bạn  <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/">Action</a></li>
                                    <li><a href="/">Another action</a></li>
                                    <li><a href="/">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="/">Separated link</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Việt Nam <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/">Action</a></li>
                                    <li><a href="/">Another action</a></li>
                                    <li><a href="/">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="/">Separated link</a></li>
                                </ul>
                            </div>
                            <div class="btn-group">
                                <a type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    VNĐ <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="/">Action</a></li>
                                    <li><a href="/">Another action</a></li>
                                    <li><a href="/">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="/">Separated link</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="header-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="logo">
                            <a href="/" alt="logo">
                                <img src="/public/assets/images/logo.png" class="img-responsive"/>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-5 col-xs-10">
                        <div class="main-search">
                            <form id="search" >
                                <div class="input-group">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-default dropdown-toggle border-primary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Nhãn hàng <span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            <li><a href="/">Action</a></li>
                                            <li><a href="/">Another action</a></li>
                                            <li><a href="/">Something else here</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="/">Separated link</a></li>
                                        </ul>
                                    </div><!-- /btn-group -->
                                    <input type="text" class="form-control" aria-label="..." placeholder="Nhập từ khoá mà bạn muốn tìm kiếm...">
                                    <span class="input-group-btn">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </span>
                                </div><!-- /input-group -->
                            </form>

                        </div>

                    </div>
                    <div class="col-md-1 col-xs-2 none-padding">
                        <div class="order">
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <a class="btn btn-default border-primary">
                                        <i class="fa fa-shopping-cart color-primary"></i>

                                    </a>
                                </div>
                                <span class="input-group-btn">
                                    <button class="btn btn-default border-primary" type="button">
                                        2
                                    </button>
                                </span>
                            </div>


                        </div>

                    </div>
                </div>
            </div>
        </div>

    </header>
    <div class="navbar navbar-default nav-menu">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/">Trang chủ<span class="sr-only">(current)</span></a></li>
                    <li><a href="/">Đồ Nam<sup class="bgcolor-yellow">Sale off</sup></a></li>
                    <li><a href="/">Đồ Nữ<sup class="bgcolor-red">New</sup></a></li>
                    <li><a href="/">Thương Hiệu</a></li>
                    <li><a href="/">Cửa Hàng</a></li>
                    <li><a href="/">Khuyến mãi</a></li>
                    <li><a href="/">Tin mới</a></li>
                    <li><a href="/">Liên hệ</a></li>
                </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </div>
    <!--breadcrumb -->
    <div class="container">
        <div class="crumb">
            <span>
                <a href="/">Trang chủ</a>
            </span>
            <span class="current">Đồ nữ</span>
        </div>
    </div><!--breadcrumb -->

    <section id="slideshow" class="container slide">
        <img src="/public/assets/images/slide.png" class="img-responsive"/>
        <img src="/public/assets/images/slide.png" class="img-responsive"/>
        <img src="/public/assets/images/slide.png" class="img-responsive"/>
    </section>

