
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4 col-xs-5">
                <img class="img-thumbnail img-responsive" src="<?php echo $this->item['image']; ?>"/>
            </div>
            <div class="col-md-8 col-xs-7">
                <h1><?php echo $this->item['name']; ?></h1>
                <div class="info">
                    <div class="star">
                        <div id="star"><input type=hidden name="rating"/></div>
                    </div>
                    <div class="hits">
                        <span>3 Lượt xem</span>
                        <span> | </span>
                        <a href="#">Thêm vào giỏ hàng </a>
                    </div>

                    <article>
                        <div class="price">
                            <p><strike>
                                <?php
                                if ($this->item['price_old']):
                                    ?>
                                    <?php echo new Zend_Currency(array("value" => $this->item['price_old'], 'precision' => 0, 'symbol' => 'VNĐ', 'format' => 'vi')); ?>
                                <?php endif; ?>
                            </strike></p><p>
                                <span><?php echo new Zend_Currency(array("value" => $this->item['price'], 'precision' => 0, 'symbol' => 'VNĐ', 'format' => 'vi')); ?></span></p>
                        </div>

                        <p align="center" class="checkout hidden">
                            <a class="btn btn-darkness text-center btn-upper">
                                Thanh toán
                            </a> 
                        </p>
                        <p>
                            <?php echo $this->item['descriptions']; ?>
                        </p>
                    </article>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        <div id="fb-root"></div>
        <script>(function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5&appId=1143384549034929";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
        <div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5" data-width="100%"></div>
    </div>
</div>

<h1 align="center">Sản phẩm cùng loại khác</h1>
<div class="products-large" id="products">
    <div class="row">
        <?php if ($this->list): ?>
            <?php foreach ($this->list as $item) : ?>
                <div class="col-md-4">
                    <div class="product">
                        <div class="row">
                            <div class="col-md-12 col-sm-6 col-xs-12">
                                <a href="/product/view/id/<?php echo $item['id']; ?>" alt="link">
                                    <img src="<?php echo $item['image']; ?>" class="img-responsive"/>
                                </a>
                            </div>
                            <div class="col-md-12 col-sm-6 col-xs-12">
                                <div class="action">
                                    <button class="btn btn-dark btn-upper btn-sm btn-50"><i class="fa fa-search"></i>  Xem nhanh</button><button class="btn btn-gray btn-upper btn-sm btn-25"><i class="fa fa-heart"></i></button><button class="btn btn-gray btn-upper btn-sm btn-25"><i class="fa fa-toggle-on"></i></button>
                                </div>

                                <div class="info">
                                    <div class="star" id="star">
                                        <div class="stars-default"><input type=hidden name="rating"/></div>
                                    </div>
                                    <div class="hits">
                                        <span>3 Lượt xem</span>
                                        <span> | </span>
                                        <a href="#">Thêm vào giỏ hàng </a>
                                    </div>
                                    <div class="decor"></div>

                                    <article>
                                        <a href="/product/view/id/<?php echo $item['id']; ?>" alt="link">
                                            <h4><?php echo $item['name']; ?></h4>
                                        </a>
                                        <div class="price">
                                            <strike>
                                                <?php
                                                if ($item['price_old']):
                                                    ?>
                                                    <?php echo new Zend_Currency(array("value" => $item['price_old'], 'precision' => 0, 'symbol' => 'VNĐ', 'format' => 'vi')); ?>
                                                <?php endif; ?>
                                            </strike>
                                            <span><?php echo new Zend_Currency(array("value" => $item['price'], 'precision' => 0, 'symbol' => 'VNĐ', 'format' => 'vi')); ?></span>
                                            <span class="sale">-10%</span>
                                        </div>

                                        <p align="center" class="checkout hidden">
                                            <a class="btn btn-darkness text-center btn-upper">
                                                Thanh toán
                                            </a> 
                                        </p>

                                    </article>
                                </div>

                            </div>

                        </div>

                    </div>
                </div>

            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
<script>
 $("#stars").rating('create', {value: 3});
</script>