<?php echo $this->render('site/header.phtml'); ?>

<section class="content-main container">
    <div class="row">
        <div class="col-md-3">
            <?php echo $this->render('site/widget.phtml'); ?>
        </div>
        <div class="col-md-9">
            <div class="list-products">
                <?php echo $this->layout()->content; ?>

            </div>

        </div>
</section>
<?php
echo $this->render('site/footer.phtml');
