<div class="row">
    <div class="col-md-3">
        <a href="/admin/categories">
            <span class="headding"><i class="fa fa-gears"></i> Danh mục
            </span>
        </a>
    </div>
    <div class="col-md-3">
         <a href="/admin/manufacturers">
            <span class="headding"><i class="fa fa-gears"></i> Nhà SX
            </span>
        </a>
    </div>
    <div class="col-md-3">
        <a href="/admin/products">
            <span class="headding"><i class="fa fa-gears"></i> Sản phẩm
            </span>
        </a>
    </div>
    <div class="col-md-3">
        <a href="/admin">
            <span class="headding"><i class="fa fa-gears"></i> Giỏ hàng
            </span>
        </a>
    </div>
</div>