<div class = "features_items"><!--features_items-->
    <h2 class = "title text-center">Danh Mục Sản Phẩm <span><a href="/admin/products/edit/add" class="btn btn-xs btn-info">Thêm mới</a></span></h2>
    <div class = "row">
        <div class = "col-lg-12">

            <?php if (isset($this->form)) { ?>
                <div class="row">
                    <div class="col-md-6">
                        <?php
                        echo $this->form;
                        ?>
                    </div>
                    <div class="col-md-6">
                        <?php if ($this->item['image']): ?>
                            <img class="img-responsive img-thumbnail" src="<?php echo $this->item['image'] ?>" />
                        <?php endif; ?>

                    </div>
                </div>
                <a href="/admin/products" class="btn btn-default">Trở lại xem danh sách</a>
                <?php
            } else {
                ?>
                <table class="table table-hover table-responsive table-striped table-bordered">
                    <thead>
                        <tr>
                        <tr>
                            <th>ID</th>
                            <th>Tên Sản Phẩm</th>
                            <th>Giá</th>
                            <th>Danh mục</th>
                            <th>Nhà sản xuất</th>
                            <th>Thao tác</th>
                        </tr>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $i = 0;
                        foreach ($this->list as $key => $value) {
                            ?>
                            <tr>
                                <td><?php echo $value['id']; ?></td>
                                <td><?php echo $value['name']; ?></td>
                                <td><?php echo $value['price']; ?></td>
                                <td><?php echo $this->categories()[$value['category_id']]; ?></td>
                                <td><?php echo $this->manufacturers()[$value['manufacturer_id']]; ?></td>
                                <td><a type="button" href="/admin/products/edit/<?php echo $value['id']; ?>" class="btn btn-info btn-xs" id="edit-categories-<?php echo $value['id']; ?>">Sửa</a>&nbsp;<a type="button" href="/admin/products/delete/<?php echo $value['id']; ?>" class="btn btn-danger btn-xs" id="edit-categories-<?php echo $value['id']; ?>">Xoá</a></td>
                            </tr>
                        <?php }
                        ?>
                    </tbody>
                </table>
                <?php
            }
            ?>
        </div>

    </div>

</div>
<?php
if ($this->item) {
    ?>
    <script>
        jQuery(document).ready(function () {
            jQuery('input[name="id"]').val('<?php echo $this->item['id']; ?>');
            jQuery('input[name="name"]').val('<?php echo $this->item['name']; ?>');
            jQuery('input[name="price_old"]').val('<?php echo $this->item['price_old']; ?>');
            jQuery('input[name="price"]').val('<?php echo $this->item['price']; ?>');
            jQuery('input[name="descriptions"]').val('<?php echo $this->item['descriptions']; ?>');
            jQuery('select[name="category_id"]').val(<?php echo $this->item['category_id']; ?>).trigger('chosen:updated');
            jQuery('select[name="manufacturer_id"]').val(<?php echo $this->item['manufacturer_id']; ?>).trigger('chosen:updated');
            jQuery('select[name="size_id"]').val(<?php echo $this->item['size_id']; ?>).trigger('chosen:updated');
            jQuery('select[name="color_id"]').val(<?php echo $this->item['color_id']; ?>).trigger('chosen:updated');
        });
    </script>
    <?php
}
?>